# Generated by Django 5.0.7 on 2026-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
